---
shared:
  :applications:
    - on_submission_trn
  :private_childcare_providers:
    - registered_person_name
  :registration_interests:
    - email
  :users:
    - trn
    - email
    - full_name
    - preferred_name
